language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true

addons:
    postgresql: "10"
    apt:
        packages:
            - postgresql-10
            - postgresql-client-10

cache: cargo

env:
    global:
        - PGPORT=5433
        - SQLITE_URL=db.sqlite3
        - MYSQL_URL=mysql://travis@localhost/twinscroll
        - PG_URL=postgres://postgres@localhost:${PGPORT}/twinscroll

services:
    - mysql
    - postgresql

before_script:
    - psql -c "CREATE DATABASE twinscroll;" -U postgres
    - psql -c "CREATE TABLE identities (token TEXT PRIMARY KEY, userid TEXT NOT NULL);" -U postgres -d twinscroll
    - psql -c "INSERT INTO identities (token, userid) VALUES ('g8mlRUwF1AKx7/ZRvReQ+dRhGpoDAzIC', 'admin');" -U postgres -d twinscroll
    - mysql -e "CREATE DATABASE twinscroll;" -u root
    - mysql -e "CREATE TABLE identities (token CHAR(32) PRIMARY KEY, userid TEXT NOT NULL);" -u root -D twinscroll
    - mysql -e "INSERT INTO identities (token, userid) VALUES ('g8mlRUwF1AKx7/ZRvReQ+dRhGpoDAzIC', 'admin');" -u root -D twinscroll
    - sqlite3 ${SQLITE_URL} "CREATE TABLE identities (token TEXT PRIMARY KEY, userid TEXT NOT NULL);"
    - sqlite3 ${SQLITE_URL} "INSERT INTO identities (token, userid) VALUES ('g8mlRUwF1AKx7/ZRvReQ+dRhGpoDAzIC', 'admin');" 

script:
    - cargo build --verbose
    - cargo test --verbose
