language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true

addons:
    postgresql: "9.6"

cache: cargo

env:
    global:
        - PGPORT=5432
        - PGUSER=postgres
        - MYSQLUSER=travis
        - SQLITE_URL=db.sqlite3
        - MYSQL_URL=mysql://${MYSQLUSER}@localhost/twinscroll
        - PG_URL=postgres://${PGUSER}@localhost:${PGPORT}/twinscroll

services:
    - mysql
    - postgresql

before_script:
    - psql -c "CREATE DATABASE twinscroll;" -U ${PGUSER}
    - psql -c "CREATE TABLE identities (token TEXT PRIMARY KEY, userid TEXT NOT NULL);" -U ${PGUSER} -d twinscroll
    - psql -c "INSERT INTO identities (token, userid) VALUES ('g8mlRUwF1AKx7/ZRvReQ+dRhGpoDAzIC', 'admin');" -U ${PGUSER} -d twinscroll
    - mysql -e "CREATE DATABASE twinscroll;" -u ${MYSQLUSER}
    - mysql -e "CREATE TABLE identities (token CHAR(32) PRIMARY KEY, userid TEXT NOT NULL);" -u ${MYSQLUSER} -D twinscroll
    - mysql -e "INSERT INTO identities (token, userid) VALUES ('g8mlRUwF1AKx7/ZRvReQ+dRhGpoDAzIC', 'admin');" -u ${MYSQLUSER} -D twinscroll
    - sqlite3 ${SQLITE_URL} "CREATE TABLE identities (token TEXT PRIMARY KEY, userid TEXT NOT NULL);"
    - sqlite3 ${SQLITE_URL} "INSERT INTO identities (token, userid) VALUES ('g8mlRUwF1AKx7/ZRvReQ+dRhGpoDAzIC', 'admin');" 

script:
    - cargo build --verbose
    - cargo test --verbose
