language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
        - rust: nightly
    fast_finish: true

addons:
    postgresql: "9.6"

cache: cargo

env:
    global:
        - SQLITE_PATH='.'
        - SQLITE_DB=db.sqlite3
        - SQLITE_DB2=db2.sqlite3
        - SQLITE_DB3=db3.sqlite3
        - MYSQL_USER=travis
        - MYSQL_HOST=localhost
        - MYSQL_DB=twinscroll
        - PG_USER=postgres
        - PG_HOST=localhost
        - PG_DB=testdb

services:
    - mysql
    - postgresql

before_script:
    - psql -f sql/postgres.sql -U ${PG_USER}
    - psql -f tests/load.sql -d ${PG_DB} -U ${PG_USER}
    - mysql -u ${MYSQL_USER} < sql/mysql.sql
    - mysql -u ${MYSQL_USER} -D ${MYSQL_DB} < tests/load.sql
    - sqlite3 ${SQLITE_DB} < sql/sqlite.sql
    - sqlite3 ${SQLITE_DB} < tests/load.sql
    - sqlite3 ${SQLITE_DB2} < sql/sqlite.sql
    - sqlite3 ${SQLITE_DB2} < tests/load.sql
    - sqlite3 ${SQLITE_DB3} < sql/sqlite.sql
    - sqlite3 ${SQLITE_DB3} < tests/load.sql

script:
    - cargo build --verbose
    - cargo test --verbose
